spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test_db
      authentication-database: admin
      username: root
      password: root
      database: test_db
      port: 27017
      host: localhost